---
- name: 注释 mirrorlist 行
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^mirrorlist="
    line: "#mirrorlist="
    backrefs: true
    backup: true
  loop: "{{ common_rocky_repo_files }}"

- name: 替换 baseurl 源
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^#baseurl=http://dl.rockylinux.org/\\$contentdir"
    line: "baseurl={{ common_rocky_repo_baseurl }}"
    backrefs: true
    backup: true
  loop: "{{ common_rocky_repo_files }}"

- name: 更新缓存
  ansible.builtin.command:
    cmd: dnf makecache
  changed_when: false
